const express=require("express")
const app=express()
const cors=require("cors")
const mongoose=require("mongoose")
const path=require("path")
const dotenv=require("dotenv")
app.use(express.json())
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));
dotenv.config()
app.use(cors())
const contactRoute=require("./route/contact")
const taskPrioriterRoute=require("./route/taskPrioriter")
const videoWatchLaterRoute=require("./route/videoWatchLater")
const quoteRoute=require("./route/quote")
const bookRoute=require("./route/book")
const blogRoute=require("./route/blog")
const postsRoute=require("./route/postsEmbed")
const websiteVideoWatchLaterRoute=require('./route/websiteVideoWatchLater')

mongoose.connect("mongodb+srv://abinandhan:hqzzdU3vLepl8gY8@cluster0.2x76hsn.mongodb.net/personalData")
.then(()=>console.log("Mongodb connected successfully"))
.catch((error)=>console.log("Error while connecting mongoDb",error))

app.use('/contact',contactRoute)
app.use("/taskPrioriter",taskPrioriterRoute)
app.use('/videoWatchLater',videoWatchLaterRoute)
app.use('/quote',quoteRoute)
app.use('/book',bookRoute)
app.use('/blog',blogRoute)
app.use('/post',postsRoute)
app.use('/websiteVideoWatchLater',websiteVideoWatchLaterRoute)
app.listen(3000,()=>{
    console.log("Server is running in localhost:3000")
})